export const ErrorCode = {
  NOT_FOUND: 'USER_NOT_FOUND',
  PHONE_NUMBER_INVALID: 'phoneNumber must be a phone number',
  EMAIL_EXISTED: 'error.EMAIL_EXISTED',
  CODE_INVALID: 'error.CODE_INVALID',
  PHONE_NUMBER_EXISTED: 'error.PHONENUMBER_EXISTED',
  INVALID_BID: 'error.INVALID_BID',
  INVALID_STATUS: 'error.INVALID_STATUS',
  PAYMENT_METHOD_EXISTED: 'error.PAYMENT_METHOD_EXISTED',
};
