// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../src/components/AComponent/AComponent.stories');
  require('../src/components/AgentItem/AgentItem.stories');
  require('../src/components/Alert/Alert.stories');
  require('../src/components/Banner/Banner.stories');
  require('../src/components/Button/Button.stories');
  require('../src/components/Button/CustomButton.stories');
  require('../src/components/Button/DatePickerSection.stories');
  require('../src/components/Chart/PieChartWithLegends.stories');
  require('../src/components/Checkbox/CheckBox.stories');
  require('../src/components/DropDown/InterestedAreaContainer.stories');
  require('../src/components/Icon.stories');
  require('../src/components/Input.stories');
  require('../src/components/LazyList.stories');
  require('../src/components/List/EmptyListView.stories');
  require('../src/components/List/TimeLineList.stories');
  require('../src/components/Modal/BadWordModal.stories');
  require('../src/components/ProjectItem/ProjectItem.stories');
  require('../src/components/PropertyItem/C2CPropertyItem.stories');
  require('../src/components/PropertyItem/HomePropertyItem.stories');
  require('../src/components/PropertyItem/ItemGuaranteedProperty.stories');
  require('../src/components/PropertyItem/ItemProperty.stories');
  require('../src/components/PropertyItem/PropertyItemCrawler.stories');
  require('../src/components/PropertyItem/ViewBrokerInfo.stories');
  require('../src/components/Rating/RatingComponent.stories');
  require('../src/components/Skeleton/Skeleton.stories');
  require('../src/components/Slider/SliderWith2Inputs.stories');
  require('../src/components/Slider/SliderWithInput.stories');
  require('../src/components/TabBar/BottomMenu.stories');
  require('../src/components/TransactionInfo.stories');
  require('../src/components/WorkingAreas.stories');
  require('../src/screens/AgentManagement/AgentManagementScreen.stories');
  require('../src/screens/Auth/AuthComponents/ConfirmOTPComponent.stories');
  require('../src/screens/Auth/ForgotPassword/ChangePasswordScreen.stories');
  require('../src/screens/Auth/ForgotPassword/ForgotPasswordScreen.stories');
  require('../src/screens/Auth/LoginScreen.stories');
  require('../src/screens/Auth/SignUp/InfoAccountScreen.stories');
  require('../src/screens/Auth/SignUp/InfoTopenerScreen.stories');
  require('../src/screens/Auth/SignUp/WellcomeScreen.stories');
  require('../src/screens/BookingDeposit/Confirm/Components/ConfirmInformation.stories');
  require('../src/screens/BookingDeposit/Confirm/SelectPaymentMethod.stories');
  require('../src/screens/BookingDeposit/ConfirmProperty/ConfirmDepositContainer.stories');
  require('../src/screens/BookingDeposit/ConfirmProperty/ConfirmProperty.stories');
  require('../src/screens/BookingDeposit/ConfirmProperty/ConfirmPropertyMainInfo.stories');
  require('../src/screens/BookingDeposit/ConfirmProperty/SecondInfoMainRow.stories');
  require('../src/screens/BookingDeposit/ConfirmProperty/UpdateUserInfoTransaction.stories');
  require('../src/screens/BookingDeposit/Success/PaymentSuccessScreen.stories');
  require('../src/screens/Call/Call.stories');
  require('../src/screens/Chat/components/ConversationItem.stories');
  require('../src/screens/Home/components/Intro/Intro.stories');
  require('../src/screens/Home/components/PlusServiceBlock/PlusServices.stories');
  require('../src/screens/Home/NewsHome/NewsItem.stories');
  require('../src/screens/Home/TopenerOfMonth/AgentRank.stories');
  require('../src/screens/LiveChat/LiveChatRoom.stories');
  require('../src/screens/ManageBuyRequest/ContactDetail/RequestDetailScreenComponents/RequestDetailInfoView.stories');
  require('../src/screens/ManageBuyRequest/ContactDetail/TradingDepositDetailInputComponents/Components/TradingDepositInput1View.stories');
  require('../src/screens/ManageBuyRequest/ContactDetail/TradingDepositDetailInputComponents/Components/TradingDepositInput2View.stories');
  require('../src/screens/ManageBuyRequest/ManageContactList/ManageBuyRequestComponents/ItemContactTrading.stories');
  require('../src/screens/ManageContactAdvice/components/ContactAdvice.stories');
  require('../src/screens/ManagePost/Contact/ContactToBuy/ContactTrading.stories');
  require('../src/screens/ManagePost/Contact/ContactTradingSuccess.stories');
  require('../src/screens/ManagePost/NewPost/NewPostComponents/CreatePostProperty.stories');
  require('../src/screens/ManagePost/ReviewPropertyPost/ViewPropertyPost.stories');
  require('../src/screens/MessageNotification/components/ListcheckHighlightItems.stories');
  require('../src/screens/Pages/InvestorInformation/InvestorDetail.stories');
  require('../src/screens/Pages/InvestorInformation/ItemInvestor.stories');
  require('../src/screens/Pages/ShareApplication/ShareApplicationView.stories');
  require('../src/screens/PlusService/LoansServicesScreen.stories');
  require('../src/screens/PlusService/PlusServiceScreen.stories');
  require('../src/screens/Profile/CreateEditProfile/BasicProfile.stories');
  require('../src/screens/Profile/ProfileScreen.stories');
  require('../src/screens/ProjectDetail/components/Text.stories');
  require('../src/screens/ProjectDetail/ProjectDetail.stories');
  require('../src/screens/PropertyChangeConfirm/Policies.stories');
  require('../src/screens/PropertyChangeConfirm/PropertyChangeConfirmScreen.stories');
  require('../src/screens/Search/components/Filter.stories');
  require('../src/screens/Search/components/FilterAgentContainer.stories');
  require('../src/screens/Search/components/ResultSearch/ResultSearch.stories');
  require('../src/screens/Search/components/SearchHeader.stories');
  require('../src/screens/SlotSelection/components/FloorSection.stories');
  require('../src/screens/SlotSelection/FloorView.stories');
  require('../src/screens/SlotSelection/ModalSelectFloor.stories');
  require('../src/screens/SlotSelection/PropertyItem.stories');
  require('../src/screens/SlotSelection/PropertyNumberInfo.stories');
  require('../src/screens/SlotSelection/SlotSelectionFilter.stories');
  require('../src/screens/Transaction/DetailTransaction/Components/BottomInfoTransaction.stories');
}

const stories = [
  '../src/components/AComponent/AComponent.stories',
  '../src/components/AgentItem/AgentItem.stories',
  '../src/components/Alert/Alert.stories',
  '../src/components/Banner/Banner.stories',
  '../src/components/Button/Button.stories',
  '../src/components/Button/CustomButton.stories',
  '../src/components/Button/DatePickerSection.stories',
  '../src/components/Chart/PieChartWithLegends.stories',
  '../src/components/Checkbox/CheckBox.stories',
  '../src/components/DropDown/InterestedAreaContainer.stories',
  '../src/components/Icon.stories',
  '../src/components/Input.stories',
  '../src/components/LazyList.stories',
  '../src/components/List/EmptyListView.stories',
  '../src/components/List/TimeLineList.stories',
  '../src/components/Modal/BadWordModal.stories',
  '../src/components/ProjectItem/ProjectItem.stories',
  '../src/components/PropertyItem/C2CPropertyItem.stories',
  '../src/components/PropertyItem/HomePropertyItem.stories',
  '../src/components/PropertyItem/ItemGuaranteedProperty.stories',
  '../src/components/PropertyItem/ItemProperty.stories',
  '../src/components/PropertyItem/PropertyItemCrawler.stories',
  '../src/components/PropertyItem/ViewBrokerInfo.stories',
  '../src/components/Rating/RatingComponent.stories',
  '../src/components/Skeleton/Skeleton.stories',
  '../src/components/Slider/SliderWith2Inputs.stories',
  '../src/components/Slider/SliderWithInput.stories',
  '../src/components/TabBar/BottomMenu.stories',
  '../src/components/TransactionInfo.stories',
  '../src/components/WorkingAreas.stories',
  '../src/screens/AgentManagement/AgentManagementScreen.stories',
  '../src/screens/Auth/AuthComponents/ConfirmOTPComponent.stories',
  '../src/screens/Auth/ForgotPassword/ChangePasswordScreen.stories',
  '../src/screens/Auth/ForgotPassword/ForgotPasswordScreen.stories',
  '../src/screens/Auth/LoginScreen.stories',
  '../src/screens/Auth/SignUp/InfoAccountScreen.stories',
  '../src/screens/Auth/SignUp/InfoTopenerScreen.stories',
  '../src/screens/Auth/SignUp/WellcomeScreen.stories',
  '../src/screens/BookingDeposit/Confirm/Components/ConfirmInformation.stories',
  '../src/screens/BookingDeposit/Confirm/SelectPaymentMethod.stories',
  '../src/screens/BookingDeposit/ConfirmProperty/ConfirmDepositContainer.stories',
  '../src/screens/BookingDeposit/ConfirmProperty/ConfirmProperty.stories',
  '../src/screens/BookingDeposit/ConfirmProperty/ConfirmPropertyMainInfo.stories',
  '../src/screens/BookingDeposit/ConfirmProperty/SecondInfoMainRow.stories',
  '../src/screens/BookingDeposit/ConfirmProperty/UpdateUserInfoTransaction.stories',
  '../src/screens/BookingDeposit/Success/PaymentSuccessScreen.stories',
  '../src/screens/Call/Call.stories',
  '../src/screens/Chat/components/ConversationItem.stories',
  '../src/screens/Home/components/Intro/Intro.stories',
  '../src/screens/Home/components/PlusServiceBlock/PlusServices.stories',
  '../src/screens/Home/NewsHome/NewsItem.stories',
  '../src/screens/Home/TopenerOfMonth/AgentRank.stories',
  '../src/screens/LiveChat/LiveChatRoom.stories',
  '../src/screens/ManageBuyRequest/ContactDetail/RequestDetailScreenComponents/RequestDetailInfoView.stories',
  '../src/screens/ManageBuyRequest/ContactDetail/TradingDepositDetailInputComponents/Components/TradingDepositInput1View.stories',
  '../src/screens/ManageBuyRequest/ContactDetail/TradingDepositDetailInputComponents/Components/TradingDepositInput2View.stories',
  '../src/screens/ManageBuyRequest/ManageContactList/ManageBuyRequestComponents/ItemContactTrading.stories',
  '../src/screens/ManageContactAdvice/components/ContactAdvice.stories',
  '../src/screens/ManagePost/Contact/ContactToBuy/ContactTrading.stories',
  '../src/screens/ManagePost/Contact/ContactTradingSuccess.stories',
  '../src/screens/ManagePost/NewPost/NewPostComponents/CreatePostProperty.stories',
  '../src/screens/ManagePost/ReviewPropertyPost/ViewPropertyPost.stories',
  '../src/screens/MessageNotification/components/ListcheckHighlightItems.stories',
  '../src/screens/Pages/InvestorInformation/InvestorDetail.stories',
  '../src/screens/Pages/InvestorInformation/ItemInvestor.stories',
  '../src/screens/Pages/ShareApplication/ShareApplicationView.stories',
  '../src/screens/PlusService/LoansServicesScreen.stories',
  '../src/screens/PlusService/PlusServiceScreen.stories',
  '../src/screens/Profile/CreateEditProfile/BasicProfile.stories',
  '../src/screens/Profile/ProfileScreen.stories',
  '../src/screens/ProjectDetail/components/Text.stories',
  '../src/screens/ProjectDetail/ProjectDetail.stories',
  '../src/screens/PropertyChangeConfirm/Policies.stories',
  '../src/screens/PropertyChangeConfirm/PropertyChangeConfirmScreen.stories',
  '../src/screens/Search/components/Filter.stories',
  '../src/screens/Search/components/FilterAgentContainer.stories',
  '../src/screens/Search/components/ResultSearch/ResultSearch.stories',
  '../src/screens/Search/components/SearchHeader.stories',
  '../src/screens/SlotSelection/components/FloorSection.stories',
  '../src/screens/SlotSelection/FloorView.stories',
  '../src/screens/SlotSelection/ModalSelectFloor.stories',
  '../src/screens/SlotSelection/PropertyItem.stories',
  '../src/screens/SlotSelection/PropertyNumberInfo.stories',
  '../src/screens/SlotSelection/SlotSelectionFilter.stories',
  '../src/screens/Transaction/DetailTransaction/Components/BottomInfoTransaction.stories',
];

module.exports = {
  loadStories,
  stories,
};
