variables:
  Feed.Name: ht-topenland/ht-topenland
  IS_CLOUD_BUILD: $[ eq(variables['POOL_NAME'], 'Azure Pipelines')]
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

pool:
  name: $(POOL_NAME)
  vmImage: 'macOS-11'
  demands:
  - AgentAndroid -equals True

trigger:
 - feature/ci-build-android

jobs:
  - job: uat_android_appium
    steps:
    - template: ./android-steps.yml
    - script: git apply patch/add-firebase-perf.diff && yarn install
      displayName: add_firebase_perf
    - script: |
        set -e
        yarn env:uat
        scripts/android-enable-screenshot.sh
        bundle exec fastlane android build_target
      displayName: build_android_uat
    - script: |
        set -ex
        mkdir -p public
        cp android/app/build/outputs/apk/release/app-release.apk public/android-uat.apk
      displayName: pre_artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'public'
        ArtifactName: 'android-uat'
        publishLocation: 'Container'
    - task: UniversalPackages@0
      inputs:
        command: publish
        publishDirectory: 'public'
        vstsFeedPublish: '$(Feed.Name)'
        vstsFeedPackagePublish: 'android-uat'
        packagePublishDescription: 'Android UAT'
