variables:
  IS_CLOUD_BUILD: $[ eq(variables['POOL_NAME'], 'Azure Pipelines')]

pool:
  name: $(POOL_NAME)
  vmImage: 'macOS-11'
  demands:
  - AgentE2E -equals True

trigger:
 paths:
   include:
     - ".azure/*"
     - "e2e/*"
     - "**/*.stories.js"
     - "**/*.storyshot"
 branches:
  include:
    - develop
    - feature/azure-pipelines
    - feature/ci-e2e
    - feature/upgrade-*

jobs:
- job: e2e_test
  timeoutInMinutes: 90
  steps:
  - template: ./ios-setup-steps.yml

  - bash: echo "##vso[task.setvariable variable=cache_prefix;isOutput=true]$BUILD_SOURCEBRANCHNAME"
    displayName: set_custom_variable
    name: customVariable

  - task: Cache@2
    inputs:
      key: '"$(CACHE_VERSION)_$(customVariable.cache_prefix)" | ios_build | "$(Agent.OS)" | "yarn.lock"'
      restoreKeys: |
        "$(CACHE_VERSION)_$(customVariable.cache_prefix)" | ios_build | "$(Agent.OS)"
        "$(CACHE_VERSION)_$(customVariable.cache_prefix)" | ios_build
      path: ios/build
    displayName: cache_ios_build
    condition: eq(variables['IS_CLOUD_BUILD'], 'true')

  - script: |
      set -e
      brew tap wix/brew
      brew install applesimutils
      yarn detox clean-framework-cache
      yarn detox build-framework-cache
    displayName: detox_setup
    condition: eq(variables['IS_CLOUD_BUILD'], 'true')

  - script: |
      set -e
      yarn env:dev
      echo "IS_TEST_IMAGE_SNAPSHOT=true" >> .env
      yarn start &
      yarn ios --simulator "iPhone 8" &>/dev/null

      export JEST_IMAGE_SNAPSHOT_TRACK_OBSOLETE=1
      export ENABLE_SCROLL_TO_BOTTOM_WHEN_CAPTURE=1
      export IS_TEST_IMAGE_SNAPSHOT=1
      yarn test:ios --artifacts-location e2e/__image_snapshots__/ --record-videos failing --take-screenshots failing
      git status
    displayName: test

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'e2e/__image_snapshots__'
      ArtifactName: 'snapshot_artifact'
      publishLocation: 'Container'
    condition: succeededOrFailed()
