export const BOOKING_DEPOSIT_ACTIONS = {
  FIELD: 'FIELD',
  CHECK_IS_BUYER: 'CHECK_IS_BUYER',
  UNCHECK_IS_BUYER: 'UNCHECK_IS_BUYER',
  SET_AGENT_DETAIL: 'SET_AGENT_DETAIL',
  SET_CONSULTANT_DETAIL: 'SET_CONSULTANT_DETAIL',
};
