const testIDs = {
  TABBAR: {
    HOME: 'TABBAR.HOME',
    CHAT: 'TABBAR.CHAT',
    CONTACT: 'TABBAR.CONTACT',
    NOTIFICATIONS: 'TABBAR.NOTIFICATIONS',
    SETTING: 'TABBAR.SETTING',
    SHOP: 'TABBAR.SHOP',
  },
  WELCOME: {
    SCREEN: 'WELCOME.SCREEN',
    IMAGE_LOGO: 'WELCOME.IMAGE_LOGO',
    TEXT_WELCOME: 'WELCOME.TEXT_WELCOME',
    BUTTON_LOGIN: 'WELCOME.BUTTON_LOGIN',
    BUTTON_SIGNUP: 'WELCOME.BUTTON_SIGNUP',
  },
  LOGIN: {
    SCREEN: 'LOGIN.SCREEN',
    IMAGE_LOGO: 'LOGIN.IMAGE_LOGO',
    TEXT_LOGIN: 'LOGIN.TEXT_LOGIN',
    BUTTON_LOGIN: 'LOGIN.BUTTON_LOGIN',
    INPUT_USERNAME: 'LOGIN.INPUT_USERNAME',
    INPUT_PASSWORD: 'LOGIN.INPUT_PASSWORD',
  },
  SIGNUP: {
    SCREEN: 'SIGNUP.SCREEN',
    IMAGE_LOGO: 'SIGNUP.IMAGE_LOGO',
    BUTTON_SIGNUP: 'SIGNUP.BUTTON_SIGNUP',
    INPUT_FIRST_NAME: 'SIGNUP.INPUT_FIRST_NAME',
    INPUT_LAST_NAME: 'SIGNUP.INPUT_LAST_NAME',
    INPUT_EMAIL: 'SIGNUP.INPUT_EMAIL',
    INPUT_PASSWORD: 'SIGNUP.INPUT_PASSWORD',
    INPUT_CONFIRM_PASSWORD: 'SIGNUP.INPUT_CONFIRM_PASSWORD',
  },
  FORGOT_PASSWORD: {
    SCREEN: 'FORGOT_PASSWORD.SCREEN',
    FORM_FORGOT: 'FORGOT_PASSWORD.FORM_FORGOT',
    FORM_NEW_PASSWORD: 'FORGOT_PASSWORD.FORM_NEW_PASSWORD',
    BUTTON_FORGOT_PASSWORD: 'FORGOT_PASSWORD.BUTTON_FORGOT_PASSWORD',
    BUTTON_SEND_PASSWORD: 'FORGOT_PASSWORD.BUTTON_SEND_PASSWORD',
    INPUT_EMAIL: 'FORGOT_PASSWORD.INPUT_EMAIL',
    INPUT_PASSWORD: 'FORGOT_PASSWORD.INPUT_PASSWORD',
    INPUT_OTP: 'FORGOT_PASSWORD.INPUT_OTP',
  },
  ONBOARD: {
    SCREEN: 'ONBOARD.SCREEN',
    BUTTON_SKIP: 'ONBOARD.BUTTON_SKIP',
  },
  HOME: {
    SCREEN: 'HOME.SCREEN',
  },
  SETTING: {
    SCREEN: 'SETTING.SCREEN',
    BUTTON_LOGOUT: 'SETTING.BUTTON_LOGOUT',
  },
  NEWSFEED: {
    SCREEN: 'NEWSFEED_ITEM.SCREEN',
    NEWSFEED_ITEM: 'NEWSFEED.NEWSFEED_ITEM',
    IMAGE_AVATAR: 'NEWSFEED.IMAGE_AVATAR',
    TEXT_NAME: 'NEWSFEED.TEXT_NAME',
    TEXT_CONTENT: 'NEWSFEED.TEXT_CONTENT',
    BUTTON_LIKE: 'NEWSFEED.BUTTON_LIKE',
    BUTTON_COMMENT: 'NEWSFEED.BUTTON_COMMENT',
    BUTTON_REPORT: 'NEWSFEED.BUTTON_REPORT',
  },
  NEWSFEED_DETAIL: {
    SCREEN: 'NEWSFEED_DETAIL.SCREEN',
    LIST: 'NEWSFEED_DETAIL.LIST',
  },
  SHOP: {
    BANNER: 'SHOP_BANNER',
    ACTION: {
      FILTER: 'SHOP_ACTION_FILTER',
    },
    FILTER: {
      SCREEN: 'SHOP_FILTER_SCREEN',
      SIZE: {
        HEADER: 'SHOP_FILTER_SIZE_HEADER',
        CONTENT: 'SHOP_FILTER_SIZE_CONTENT',
        ITEM: 'SHOP_FILTER_SIZE_ITEM',
      },
      CATEGORIES: {
        HEADER: 'SHOP_FILTER_CATEGORIES_HEADER',
        CONTENT: 'SHOP_FILTER_CATEGORIES_CONTENT',
        SEARCH: 'SHOP_FILTER_CATEGORIES_SEARCH',
        CHECK: 'SHOP_FILTER_CATEGORIES_CHECK',
        UNCHECK: 'SHOP_FILTER_CATEGORIES_UNCHECK',
      },
      COLORS: {
        HEADER: 'SHOP_FILTER_COLORS_HEADER',
        CONTENT: 'SHOP_FILTER_COLORS_CONTENT',
        ITEM: 'SHOP_FILTER_COLORS_ITEM',
        CHECK_IMAGE: 'SHOP_FILTER_COLORS_CHECK_IMAGE',
      },
      BRANDS: {
        HEADER: 'SHOP_FILTER_BRANDS_HEADER',
        CONTENT: 'SHOP_FILTER_BRANDS_CONTENT',
        SEARCH: 'SHOP_FILTER_BRANDS_SEARCH',
        CHECK: 'SHOP_FILTER_BRANDS_CHECK',
        UNCHECK: 'SHOP_FILTER_BRANDS_UNCHECK',
      },
      PRICE: {
        HEADER: 'SHOP_FILTER_PRICE_HEADER',
        CONTENT: 'SHOP_FILTER_PRICE_CONTENT',
      }
    },
    CART: {
      ICON: 'SHOP_CART_ICON',
      SCREEN: 'SHOP_CART_SCREEN',
      PRODUCT: 'SHOP_CART_PRODUCT_ITEM',
      PRODUCT_SCROLL_VIEW: 'SHOP_CART_PRODUCT_SCROLL_VIEW',
      ADD: 'SHOP_CART_ADD',
      ADD_PRODUCT_SCREEN: 'SHOP_CART_ADD_PRODUCT_SCREEN',
      BACK: 'SHOP_CART_BACK',
      SWIPE_ITEM: 'SHOP_CART_SWIPE_ITEM',
      ADD_QUANTITY: 'SHOP_CART_ADD_QUANTITY',
      SUBTRACT_QUANTITY: 'SHOP_CART_SUBTRACT_QUANTITY',
      QUANTITY: 'SHOP_CART_QUANTITY',
      SWIPE_ITEM_CANCEL: 'SHOP_CART_SWIPE_ITEM_CANCEL',
      SWIPE_ITEM_LIKE: 'SHOP_CART_SWIPE_ITEM_LIKE',
      SUBTOTAL: 'SHOP_CART_SUBTOTAL',
      CHECK_OUT: 'SHOP_CART_CHECK_OUT',
    }
  },
}

module.exports = testIDs;
