import { normalize } from '@/vars/normalize';
import { isIOS } from '@/shared/devices';

export const fonts: any = {
  size: {
    s8: normalize(8),
    s9: normalize(9),
    s10: normalize(10),
    s11: normalize(11),
    s12: normalize(12),
    s13: normalize(13),
    s14: normalize(14),
    s15: normalize(15),
    s16: normalize(16),
    s17: normalize(17),
    s18: normalize(18),
    s19: normalize(19),
    s20: normalize(20),
    s21: normalize(21),
    s22: normalize(22),
    s23: normalize(23),
    s24: normalize(24),
    s25: normalize(25),
    s26: normalize(26),
    s27: normalize(27),
    s28: normalize(28),
    s29: normalize(29),
    s30: normalize(30),
    s31: normalize(31),
    s32: normalize(32),
    s33: normalize(33),
    s34: normalize(34),
    s35: normalize(35),
    s36: normalize(36),
    s37: normalize(37),
    s38: normalize(38),
    s39: normalize(39),
    s40: normalize(40),
    s41: normalize(41),
    s42: normalize(42),
    s43: normalize(43),
    s44: normalize(44),
    s45: normalize(45),
    s46: normalize(46),
    s47: normalize(47),
    s48: normalize(48),
    s49: normalize(49),
    s50: normalize(50),
  },
  family: {
    SSPBlack: 'SourceSansPro-Black',
    SSPBlackItalic: 'SourceSansPro-BlackItalic',
    SSPBold: 'SourceSansPro-Bold',
    SSPBoldItalic: 'SourceSansPro-BoldItalic',
    SSPExtraLight: 'SourceSansPro-ExtraLight',
    SSPExtraLightItalic: 'SourceSansPro-ExtraLightItalic',
    SSPItalic: 'SourceSansPro-Italic',
    SSPLight: 'SourceSansPro-Light',
    SSPLightItalic: 'SourceSansPro-LightItalic',
    SSPRegular: 'SourceSansPro-Regular',
    SSPSemiBold: 'SourceSansPro-SemiBold',
    SSPSemiBoldItalic: 'SourceSansPro-SemiBoldItalic',
    MABlack: 'MontserratAlternates-Black',
    PoppinsRegular: 'Poppins-Regular',
    PoppinsMedium: 'Poppins-Medium',
    PoppinsMediumItalic: 'Poppins-MediumItalic',
    PoppinsSemiBold: 'Poppins-SemiBold',
    PoppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
    PoppinsBold: 'Poppins-Bold',
    PoppinsBoldItalic: 'Poppins-BoldItalic',
    RobotoRegular: 'Roboto-Regular',
    RobotoMedium: 'Roboto-Medium',
    RobotoMediumItalic: 'Roboto-MediumItalic',
    RobotoBold: 'Roboto-Bold',
    RobotoBoldItalic: 'Roboto-BoldItalic',

    PlayBold: 'Play-Bold',

    // MontserratAlternates-Black
  },
  fontWeight: {
    bold: isIOS ? '600' : 'bold',
  },
};
