/*
 * Created by IntelliJ IDEA.
 * User: kavin
 * Date: Fri Apr 09 2021
 * Time: 17:23
 */
export const Icons = {
  apple: 'ic-apple',
  facebook: 'ic-facebook',
  google: 'ic-google',
  arrowDown: 'ic-arrow-down',
  logoCharDefault: 'ic-logo-char-default',
  logoDefault: 'ic-logo-default',
  qrCode: 'ic-qr-code',
  scan: 'ic-scan',
  inProgress: 'ic-in-progress',
  time: 'ic-time',
  bookmarkLine: 'ic-bookmark-line',
  calendar: 'ic-calendar',
  checkDoubleLine: 'ic-check-double-line',
  checkNotification: 'ic-check-notification',
  checkmark: 'ic-checkmark',
  coin: 'ic-coin',
  donate: 'ic-donate',
  earth: 'ic-earth',
  editLine: 'ic-edit-line',
  heartMeeting: 'ic-heart-meeting',
  historyLine: 'ic-history-line',
  mapPinLine: 'ic-map-pin-line',
  percentage: 'ic-percentage',
  review: 'ic-review',
  settingsLine: 'ic-settings-line',
  shieldCheckLine: 'ic-shield-check-line',
  starFill: 'ic-star-fill',
  starHalf: 'ic-star-half-line',
  starLine: 'ic-star-line',
  suitcase: 'ic-suitcase',
  thanksLine: 'ic-thanks-line',
  accountFill: 'ic-account-fill',
  accountLine: 'ic-account-line',
  arrowLeft: 'ic-arrow-left',
  arrowRight: 'ic-arrow-right',
  chatFill: 'ic-chat-fill',
  chatLine: 'ic-chat-line',
  check: 'ic-check',
  uncheck: 'ic-uncheck',
  closeCircleLine: 'ic-close-circle-line',
  close: 'ic-close',
  companyLine: 'ic-company-line',
  filter: 'ic-filter',
  heartFill: 'ic-heart-fill',
  heartLine: 'ic-heart-line',
  network: 'ic-network',
  notificationFill: 'ic-notification-fill',
  notificationLine: 'ic-notification-line',
  paypal: 'ic-paypal-line',
  rotate: 'ic-rotate',
  school: 'ic-school',
  bidFill: 'ic-bid-fill',
  bidLine: 'ic-bid-line',
  homeFill: 'ic-home-fill',
  homeLine: 'ic-home-line',
  genderMale: 'ic-male',
  genderFemale: 'ic-female',
  genderOther: 'ic-gender-other',
  iconX: 'ic-x',
  plus: 'ic-plus',
  checkCustom: 'ic-check-custom',
  radioSelected: 'ic-radio-selected',
  radioUnselected: 'ic-radio-unselect',
  profileLine: 'ic-profile-line',
  tick: 'ic-tick',
};
