export const images = {
  missing: require('@/assets/icons/missing-image.png'),
  placeHolderFlatRight: require('@/assets/icons/place-holder-flat-right.png'),
  icEmptyStar: require('@/assets/icons/ic-empty-star.png'),
  icFillStar: require('@/assets/icons/ic-fill-star.png'),
  bgCard: require('@/assets/images/bg_card.png'),
  payPals: require('@/assets/images/paypals.png'),
  bgPaypal: require('@/assets/images/bg_paypal.png'),
  photoWithPeaceFingers: require('@/assets/images/photoWithPeaceFingers.png'),
  tutorial1: require('@/assets/images/tutorial/tutorialOne.png'),
  tutorial1Sp: require('@/assets/images/tutorial/tutorialOneSp.png'),
  tutorial2: require('@/assets/images/tutorial/tutorial2.png'),
  tutorial3: require('@/assets/images/tutorial/tutorial3.png'),
  tutorial5: require('@/assets/images/tutorial/tutorial5.png'),
  tutorial5Sp: require('@/assets/images/tutorial/tutorial5Sp.png'),
  tutorial6: require('@/assets/images/tutorial/tutorial6.png'),
  tutorial6Sp: require('@/assets/images/tutorial/tutorial6Sp.png'),
  tutorial7: require('@/assets/images/tutorial/tutorial7.png'),
  revertBold: require('@/assets/icons/ic-revert-bold.png'),
  thumbBid: require('@/assets/icons/thumbBid.png'),
  thumbUpPng: require('@/assets/icons/thumb-up-png.png'),
  thumbDownPng: require('@/assets/icons/thumb-down-png.png'),
  categories: require('@/assets/icons/categoriesPng.png'),
  badgeRed: require('@/assets/icons/badge-red.png'),
  badgeBlue: require('@/assets/icons/badge-blue.png'),
  backgroundApp: require('@/assets/images/background.png'),
};
