import { all, fork } from 'redux-saga/effects';
import toggleFeatureSagas from './toggleFeatureSagas';
import invoiceSagas from './invoiceSagas';
import authSagas from './authSagas';
import faqSagas from './faqSagas';
import extraServiceSagas from './extraServiceSagas';
import insuranceSagas from './insuranceSagas';
import creditSaga from './creditSagas';
import fileStorageSagas from './fileStorageSagas';
import masterDataSagas from './masterDataSagas';
import partnerSagas from './partnerSagas';
import orderSagas from './orderSagas';
import cashoutSagas from './cashoutSagas';
import paymentSagas from './paymentSagas';
import memberSaga from './memberSagas';
import depositSagas from './depositSagas';
import scheduleSagas from './scheduleSagas';
import leadSagas from './leadSagas';
import termAndConditionSagas from './termAndConditionSagas';
import linkSagas from './linkSagas';

export default function* rootSaga() {
  yield all([fork(authSagas)]);
  yield all([fork(fileStorageSagas)]);
  yield all([fork(masterDataSagas)]);
  // yield all([fork(notificationSagas)]);
  // yield all([fork(eventSagas)]);
  // yield all([fork(newsSagas)]);
  // yield all([fork(bannerSagas)]);
  // yield all([fork(offerSagas)]);
  yield all([fork(paymentSagas)]);
  // yield all([fork(contactSagas)]);
  yield all([fork(memberSaga)]);
  yield all([fork(faqSagas)]);
  // yield all([fork(saleKitSagas)]);
  // yield all([fork(profitSagas)]);
  yield all([fork(termAndConditionSagas)]);
  yield all([fork(partnerSagas)]);
  yield all([fork(leadSagas)]);
  yield all([fork(orderSagas)]);
  // yield all([fork(workflowSagas)]);
  yield all([fork(creditSaga)]);
  yield all([fork(insuranceSagas)]);
  yield all([fork(extraServiceSagas)]);
  yield all([fork(scheduleSagas)]);
  yield all([fork(invoiceSagas)]);
  yield all([fork(cashoutSagas)]);
  yield all([fork(depositSagas)]);
  yield all([fork(toggleFeatureSagas)]);
  yield all([fork(linkSagas)]);
  // yield all([fork(groupTopenerSagas)]);
  // yield all([fork(kpiSagas)]);
}
