# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ShowSourcing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShowSourcing

  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire', '~> 4.8.1'
  pod 'SDWebImage', '~> 5.0'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   'RCTGeolocation',
  # ]
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTLinkingIOS',
  ]

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'ShowSourcingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
    end

    if target.name == "React"
      target.remove_from_project
    end
  end
end
