/*
  func Helper gen actionType
*/
export const asyncTypes = action => ({
  ORIGIN: `TPF_${action}`,
  HANDLER: `TPF_${action}_HANDLER`,
  PENDING: `TPF_${action}_PENDING`,
  START: `TPF_${action}_START`,
  MORE: `TPF_${action}_MORE`,
  SUCCESS: `TPF_${action}_SUCCESS`,
  FAILURE: `TPF_${action}_FAILURE`,
  ERROR: `TPF_${action}_ERROR`,
  CLEAR: `TPF_${action}_CLEAR`,
  STORE: `TPF_${action}_STORE`,
  END: `TPF_${action}_END`
});
/*
  CONNECTIVITY
  - receive, sound notification
*/
export const CONNECTIVITY = {
  APP_CONNECTIVITY_CHANGE: asyncTypes('CONNECTIVITY/APP_CONNECTIVITY_CHANGE')
};

export const ERROR = {
  SHOW: asyncTypes('ERROR/SHOW'),
  HIDE: asyncTypes('ERROR/HIDE')
};

export const MIDDLEWARE = {
  TOGGLE_SDK: asyncTypes('MIDDLEWARE/TOGGLE_SDK'),
  SET_ACCOUNT_TOPENID: asyncTypes('MIDDLEWARE/SET_ACCOUNT_TOPENID')
};

export const AUTH = {
  GET_ACCESS_TOKEN: asyncTypes('AUTH/GET_ACCESS_TOKEN'),
  SET_LOGIN: asyncTypes('AUTH/SET_LOGIN'),
  SET_READ_ONBOARDING: asyncTypes('AUTH/SET_READ_ONBOARDING'),
  CHECK_MEMBER_IS_EXIST: asyncTypes('AUTH/CHECK_MEMBER_IS_EXIST'),
  UPDATE_REFERAL_CODE: asyncTypes('AUTH/UPDATE_REFERAL_CODE'),
  LOG_OUT: asyncTypes('AUTH/LOG_OUT'),
  SET_ACCESS_TOKEN: asyncTypes('AUTH/SET_ACCESS_TOKEN'),
  SET_LOCAL_PIN: 'AUTH/SET_LOCAL_PIN',
  REMOVE_LOCAL_PIN: 'AUTH/REMOVE_LOCAL_PIN',
  REFRESH_TOKEN: asyncTypes('AUTH/REFRESH_TOKEN'),
  GET_TOPENID_PROFILE: asyncTypes('AUTH/GET_TOPENID_PROFILE'),
  SET_FACE_ID: asyncTypes('AUTH/SET_FACE_ID'),
  SET_TOUCH_ID: asyncTypes('AUTH/SET_TOUCH_ID'),
  SET_BY_PASS_PIN_CODE: asyncTypes('AUTH/SET_BY_PASS_PIN_CODE'),
  GET_ALL_REFERRAL: asyncTypes('AUTH/GET_ALL_REFERRAL'),
  GET_LIST_REFERRAL_BY_MEMBER: asyncTypes('AUTH/GET_LIST_REFERRAL_BY_MEMBER'),
  ADD_REFERRAL_CODE: asyncTypes('AUTH/ADD_REFERRAL_CODE'),
  GET_AUTH_TOPENID_INFO: asyncTypes('AUTH/GET_AUTH_TOPENID_INFO'),
  GET_PASSWORD_PATTERN: asyncTypes('AUTH/GET_PASSWORD_PATTERN'),
  CHECK_MEMBER_TOPENER_BY_TOPENID: asyncTypes('AUTH/CHECK_MEMBER_TOPENER_BY_TOPENID'),
  CHANGE_PASSWORD: asyncTypes('AUTH/CHANGE_PASSWORD'),
  SET_LOGIN_BY_TOKEN: 'AUTH/SET_LOGIN_BY_TOKEN',
  GET_TOPEN_ID: asyncTypes('AUTH/GET_TOPEN_ID')
};

export const SYSTEM = {
  SHOW_ERROR: asyncTypes('SYSTEM/SHOW_ERROR'),
  CLEAR_ERROR: asyncTypes('SYSTEM/CLEAR_ERROR'),
  CHANGE_LANGUAGE: asyncTypes('SYSTEM/CHANGE_LANGUAGE')
};

export const NOTIFICATION = {
  UPDATE_NOTIFICATION_SETTING: asyncTypes('NOTIFICATION/UPDATE_NOTIFICATION_SETTING'),
  GET_ALL_NOTIFICATION: asyncTypes('NOTIFICATION/GET_ALL_NOTIFICATION'),
  GET_GENERAL_NOTIFICATION: asyncTypes('NOTIFICATION/GET_GENERAL_NOTIFICATION'),
  GET_PRIVATE_NOTIFICATION: asyncTypes('NOTIFICATION/GET_PRIVATE_NOTIFICATION'),
  DELETE_NOTIFICATION: asyncTypes('NOTIFICATION/DELETE_NOTIFICATION'),
  READ_NOTIFICATION: asyncTypes('NOTIFICATION/READ_NOTIFICATION'),
  GET_NOTIFICATION_SETTING: asyncTypes('NOTIFICATION/GET_NOTIFICATION_SETTING'),
  REMOVE_ALL_NOTIFICATION: asyncTypes('NOTIFICATION/REMOVE_ALL_NOTIFICATION'),
  GET_GENERAL_NOTIFICATION_HISTORY: asyncTypes('NOTIFICATION/GET_GENERAL_NOTIFICATION_HISTORY'),
  NOTIFICATION_HISTORY_CHANGE_STATUS: asyncTypes('NOTIFICATION/NOTIFICATION_HISTORY_CHANGE_STATUS'),
  DELETE_NOTIFICATION_HISTORY: asyncTypes('NOTIFICATION/DELETE_NOTIFICATION_HISTORY'),
  GET_PERSONAL_NOTIFICATION_HISTORY: asyncTypes('NOTIFICATION/GET_PERSONAL_NOTIFICATION_HISTORY'),
  GET_PROMOTION: asyncTypes('NOTIFICATION/GET_PROMOTION')
};

export const SECURITY = {
  GET_OTP_FORGET: asyncTypes('SECURITY/GET_OTP_FORGET'),
  CONFIRM_OTP_FORGET: asyncTypes('SECURITY/CONFIRM_OTP_FORGET'),
  CLEAR_ERROR: asyncTypes('SECURITY/CLEAR_ERROR'),
  CONFIRM_CURRENT_PIN_CODE: asyncTypes('SECURITY/CONFIRM_CURRENT_PIN_CODE')
};

export const MASTER_DATA = {
  GET_ALL: asyncTypes('MASTER_DATA/GET_ALL'),
  GET_ALL_TRIGGER: asyncTypes('MASTER_DATA/GET_ALL_TRIGGER'),
  GET_FLOW_BY_TRIGGER_CODE: asyncTypes('MASTER_DATA/GET_FLOW_BY_TRIGGER_CODE'),
  GET_BECOME_TOPENER: asyncTypes('MASTER_DATA/GET_BECOME_TOPENER'),
  GET_INFO_SERVICE: asyncTypes('MASTER_DATA/GET_INFO_SERVICE'),
  GET_LIST_TRIGGER: asyncTypes('MASTER_DATA/GET_LIST_TRIGGER')
};

export const PROFILE = {
  GET_PROFILE: asyncTypes('PROFILE/GET_PROFILE'),
  UPDATE_PROFILE: asyncTypes('PROFILE/UPDATE_PROFILE'),
  GET_OTP_PROFILE: asyncTypes('PROFILE/GET_OTP_PROFILE'),
  EXISTED_PROFILE: asyncTypes('PROFILE/EXISTED_PROFILE'),
  CONFIRM_CODE_PROFILE: asyncTypes('PROFILE/CONFIRM_CODE_PROFILE'),
  GET_OTP_EMAIL: asyncTypes('PROFILE/GET_OTP_EMAIL'),
  VERIFY_OTP_EMAIL: asyncTypes('PROFILE/VERIFY_OTP_EMAIL'),
  CLEAR_ERROR: asyncTypes('PROFILE/CLEAR_ERROR'),
  CLEAR_PROFILE: asyncTypes('PROFILE/CLEAR_PROFILE')
};

export const EVENT = {
  GET_HIGHLIGHT_EVENT: asyncTypes('EVENT/GET_HIGHLIGHT_EVENT'),
  GET_EVENT_LIST: asyncTypes('EVENT/GET_EVENT_LIST'),
  GET_EVENT_DETAIL: asyncTypes('EVENT/GET_EVENT_DETAIL')
};

export const BANNER = {
  GET_BANNER: asyncTypes('BANNER/GET_BANNER'),
  GET_BANNER_DETAIL: asyncTypes('BANNER/GET_BANNER_DETAIL')
};

export const FILE_STORAGE = {
  UPLOAD: asyncTypes('FILE_STORAGE/UPLOAD'),
  SCAN_ID_CARD: asyncTypes('FILE_STORAGE/SCAN_ID_CARD')
};

export const CREDIT = {
  SET_PRODUCT_FILTER: asyncTypes('CREDIT/SET_PRODUCT_FILTER'),
  SET_LEAD_CONTACT: asyncTypes('CREDIT/SET_LEAD_CONTACT'),
  GET_LOAN_PRODUCT_LIST: asyncTypes('CREDIT/GET_LOAN_PRODUCT_LIST'),
  GET_ALL_CATEGORY: asyncTypes('CREDIT/GET_ALL_CATEGORY'),
  GET_LOAN_PRODUCT_DETAIL: asyncTypes('CREDIT/GET_LOAN_PRODUCT_DETAIL'),
  GET_FINANCEDEAL_ORDER_FORM: asyncTypes('CREDIT/GET_FINANCEDEAL_ORDER_FORM'),
  GET_ORDER_LIST: asyncTypes('CREDIT/GET_ORDER_LIST'),
  GET_LIST_RESPONSES: asyncTypes('CREDIT/GET_LIST_RESPONSES'),
  COMPARE_PRODUCTS: asyncTypes('CREDIT/COMPARE_PRODUCTS'),
  GET_TOTAL_RECORD: asyncTypes('CREDIT/GET_TOTAL_RECORD'),
  SET_DEAL_NEW_FLAG: asyncTypes('CREDIT/SET_DEAL_NEW_FLAG'),
  DELETE_DEAL: asyncTypes('CREDIT/DELETE_DEAL'),
  CONFIRM_REFUND_REQUEST: asyncTypes('CREDIT/CONFIRM_REFUND_REQUEST'),
  NEED_SUPPORT: asyncTypes('CREDIT/NEED_SUPPORT'),
  GET_CREDIT_BY_CATEGORY: asyncTypes('CREDIT/GET_CREDIT_BY_CATEGORY'),
  CREATE_DEPOSIT_PAYMENT_TRANSACTION: asyncTypes('CREDIT/CREATE_DEPOSIT_PAYMENT_TRANSACTION'),
  EDIT_DEAL: asyncTypes('CREDIT/EDIT_DEAL'),
  GET_CREATE_DEAL_ORDER_FORM: asyncTypes('CREDIT/GET_CREATE_DEAL_ORDER_FORM'),
  CREATE_FINANE_DEAL_ORDER: asyncTypes('CREDIT/CREATE_FINANE_DEAL_ORDER'),
  DELETE_FINANE_DEAL_ORDER: asyncTypes('CREDIT/DELETE_FINANE_DEAL_ORDER')
};

export const NEWS = {
  GET_HIGHLIGHT_NEWS: asyncTypes('NEWS/GET_HIGHLIGHT_NEWS'),
  GET_NEWS_LIST: asyncTypes('NEWS/GET_NEWS_LIST'),
  GET_NEWS_DETAIL: asyncTypes('NEWS/GET_NEWS_DETAIL')
};

export const OFFER = {
  GET_HIGHLIGHT_OFFER: asyncTypes('OFFER/GET_HIGHLIGHT_OFFER'),
  GET_OFFER_LIST: asyncTypes('OFFER/GET_OFFER_LIST'),
  GET_OFFER_DETAIL: asyncTypes('OFFER/GET_OFFER_DETAIL')
};

export const PAYMENT = {
  GENERATE_LINK: asyncTypes('PAYMENT/GENERATE_LINK'),
  CLEAR_LINK: asyncTypes('PAYMENT/CLEAR_LINK'),
  GET_RESPONSE_PAYMENT_DATA: asyncTypes('PAYMENT/GET_RESPONSE_PAYMENT_DATA'),
  CLEAR_RESPONSE_PAYMENT_DATA: asyncTypes('PAYMENT/CLEAR_RESPONSE_PAYMENT_DATA'),
  GET_PAYMENT_RESULT: asyncTypes('PAYMENT/GET_PAYMENT_RESULT')
};
export const CONTACT = {
  GET_CONTACTS: asyncTypes('CONTACT/GET_CONTACTS'),
  GET_CONTACT_DETAIL: asyncTypes('CONTACT/GET_CONTACT_DETAIL')
};
export const MEMBER = {
  GET_PROFILE: asyncTypes('MEMBER/GET_PROFILE'),
  UPDATE_PROFILE: asyncTypes('MEMBER/UPDATE_PROFILE'),
  HIDE_BALANCE: asyncTypes('MEMBER/HIDE_BALANCE'),
  UPLOAD_AVATAR: asyncTypes('MEMBER/UPLOAD_AVATAR'),
  GET_AGENCY_INFORMATION: asyncTypes('MEMBER/GET_AGENCY_INFORMATION'),
  GET_SUBCRIPTION_TOPENERS: asyncTypes('MEMBER/GET_SUBCRIPTION_TOPENERS'),
  GET_POLICY_SUBSCRIPTION: asyncTypes('MEMBER/GET_POLICY_SUBSCRIPTION'),
  GET_MEMBER_PROFILE: asyncTypes('MEMBER/GET_MEMBER_PROFILE'),
  POST_RENEWAL_TOPENER: asyncTypes('MEMBER/POST_RENEWAL_TOPENER'),
  GET_COMMISSION_INFORMATION: asyncTypes('MEMBER/GET_COMMISSION_INFORMATION'),
  GET_TOPENID_PROFILE: asyncTypes('PROFILE/GET_TOPENID_PROFILE'),
  UPDATE_TOPEND_ID_INFO: asyncTypes('PROFILE/UPDATE_TOPEND_ID_INFO'),
  GET_ADVANCE_INFO_BY_ID: asyncTypes('MEMBER/GET_ADVANCE_INFO_BY_ID'),
  ACCEPT_LEGAL: asyncTypes('MEMBER/ACCEPT_LEGAL'),
  GET_LEGAL_IMAGE: asyncTypes('MEMBER/GET_LEGAL_IMAGE'),
  CREATE_MEMBER_FROM_SDK: asyncTypes('MEMBER/CREATE_MEMBER_FROM_SDK'),
  CREATE_TPF_MEMBER_FROM_SDK: asyncTypes('MEMBER/CREATE_TPF_MEMBER_FROM_SDK'),
  GET_POLICY_TOPENID: asyncTypes('MEMBER/GET_POLICY_TOPENID')
};
export const FAQ = {
  GET_FAQ_LIST: asyncTypes('FAQ/GET_FAQ_LIST'),
  GET_FAQ_DETAILS_LIST: asyncTypes('FAQ/GET_FAQ_DETAILS_LIST'),
  CREATE_FAQ_SUPPORT: asyncTypes('FAQ/CREATE_FAQ_SUPPORT'),
  GET_PROCESSING_FAQ_SUPPORT_LIST: asyncTypes('FAQ/GET_PROCESSING_FAQ_SUPPORT_LIST'),
  GET_CLOSED_FAQ_SUPPORT_LIST: asyncTypes('FAQ/GET_CLOSED_FAQ_SUPPORT_LIST'),
  GET_WAITING_FAQ_SUPPORT_LIST: asyncTypes('FAQ/GET_WAITING_FAQ_SUPPORT_LIST'),
  GET_FAQ_SUPPORT_DETAIL: asyncTypes('FAQ/GET_FAQ_SUPPORT_DETAIL'),
  FEEDBACK_TO_OPERATOR: asyncTypes('FAQ/FEEDBACK_TO_OPERATOR'),
  CLOSE_REQUEST: asyncTypes('FAQ/CLOSE_REQUEST'),
  GET_FAQ_SUPPORT_LIST_SUMMARY: asyncTypes('FAQ/GET_FAQ_SUPPORT_LIST_SUMMARY')
};
export const SALE_KIT = {
  GET_SUB_CATEGORY: asyncTypes('SALE_KIT/GET_SUB_CATEGORY'),
  GET_HIGHLIGHT_SALE_KIT: asyncTypes('SALE_KIT/GET_HIGHLIGHT_SALE_KIT'),
  GET_SALE_KIT_LIST: asyncTypes('SALE_KIT/GET_SALE_KIT_LIST'),
  GET_SALE_KIT_DETAIL: asyncTypes('SALE_KIT/GET_SALE_KIT_DETAIL')
};
export const TERM_AND_CONDITION = {
  GET_TERM_AND_CONDITION: asyncTypes('TERM_AND_CONDITION/GET_TERM_AND_CONDITION'),
  GET_PRIVACY_POLICY: asyncTypes('TERM_AND_CONDITION/GET_PRIVACY_POLICY')
};
export const MEMBER_PROFIT = {
  GET_MEMBER_PROFIT: asyncTypes('MEMBER_PROFIT/GET_MEMBER_PROFIT')
};
export const PARTNER = {
  GET_PARTNER_LIST: asyncTypes('PARTNER/GET_PARTNER_LIST'),
  GET_PARTNER_DETAIL: asyncTypes('PARTNER/GET_PARTNER_DETAIL')
};
export const LEAD = {
  GET_LEAD_DETAIL: asyncTypes('LEAD/GET_LEAD_DETAIL'),
  GET_LEAD_LIST: asyncTypes('LEAD/GET_LEAD_LIST'),
  CREATE_OR_EDIT: asyncTypes('LEAD/CREATE_OR_EDIT'),
  DELETE_LEAD: asyncTypes('LEAD/DELETE_LEAD'),
  UPDATE_STATUS_LEAD: asyncTypes('LEAD/UPDATE_STATUS_LEAD'),
  GET_LEAD_STATUS_SUMMARY: asyncTypes('LEAD/GET_LEAD_STATUS_SUMMARY'),
  CREATE_REQUEST: asyncTypes('LEAD/CREATE_REQUEST')
};

export const ORDER = {
  GET_ORDER_LIST: asyncTypes('ORDER/GET_ORDER_LIST'),
  GET_ORDER_DETAIL: asyncTypes('ORDER/GET_ORDER_DETAIL'),
  UPDATE_ORDER_STATUS: asyncTypes('ORDER/UPDATE_ORDER_STATUS'),
  GET_TOTAL_RECORD: asyncTypes('ORDER/GET_TOTAL_RECORD'),
  SET_ORDER_NEW_FLAG: asyncTypes('ORDER/SET_ORDER_NEW_FLAG'),
  DELETE_ORDER: asyncTypes('INSURANCE/DELETE_ORDER')
};

export const ADDITION_SERVICE = {
  GET_FORM: asyncTypes('ADDITION_SERVICE/GET_FORM'),
  SET_LEAD_CONTACT: asyncTypes('ADDITION_SERVICE/SET_LEAD_CONTACT'),
  GET_ADDITION_SERVICE_LIST: asyncTypes('ADDITION_SERVICE/GET_ADDITION_SERVICE_LIST'),
  GET_ADDITION_SERVICE_DETAIL: asyncTypes('ADDITION_SERVICE/GET_ADDITION_SERVICE_DETAIL'),
  POST_ADDITION_SERVICE_REGISTER: asyncTypes('ADDITION_SERVICE/POST_ADDITION_SERVICE_REGISTER')
};

export const WORKFLOW = {
  GET_NEW_ACTION: asyncTypes('WORKFLOW/GET_NEW_ACTION')
};

export const EXTRA_SERVICE = {
  SET_LEAD_CONTACT: asyncTypes('EXTRA_SERVICE/SET_LEAD_CONTACT'),
  GET_PRODUCT_LIST: asyncTypes('EXTRA_SERVICE/GET_PRODUCT_LIST'),
  GET_PRODUCT_DETAIL: asyncTypes('EXTRA_SERVICE/GET_PRODUCT_DETAIL'),
  GET_ORDER_FORM: asyncTypes('EXTRA_SERVICE/GET_ORDER_FORM'),
  CREATE_ORDER: asyncTypes('EXTRA_SERVICE/CREATE_ORDER'),
  GET_ORDER_LIST: asyncTypes('EXTRA_SERVICE/GET_ORDER_LIST'),
  GET_ORDER_DETAIL: asyncTypes('EXTRA_SERVICE/GET_ORDER_DETAIL'),
  UPDATE_ORDER_STATUS: asyncTypes('EXTRA_SERVICE/UPDATE_ORDER_STATUS'),
  GET_TOTAL_RECORD: asyncTypes('EXTRA_SERVICE/GET_TOTAL_RECORD'),
  CREATE_EXTRA_SERVICE_PAYMENT_TRANSACTION: asyncTypes(
    'EXTRA_SERVICE/CREATE_EXTRA_SERVICE_PAYMENT_TRANSACTION'
  ),
  EDIT_ORDER: asyncTypes('EXTRA_SERVICE/EDIT_ORDER'),
  GET_ADDED_ORDER_FORM_FOR_CREATE: asyncTypes('EXTRA_SERVICE/GET_ADDED_ORDER_FORM_FOR_CREATE')
};

export const INSURANCE = {
  SET_LEAD_CONTACT: asyncTypes('INSURANCE/SET_LEAD_CONTACT'),
  GET_INSURANCE_BY_CATEGORY: asyncTypes('INSURANCE/GET_INSURANCE_BY_CATEGORY'),
  GET_INSURANCE_CATEGORIES: asyncTypes('INSURANCE/GET_INSURANCE_CATEGORIES'),
  GET_HIGHLIGHT_INSURANCE_CATEGORIES: asyncTypes('INSURANCE/GET_HIGHLIGHT_INSURANCE_CATEGORIES'),
  GET_INSURANCE_DETAIL: asyncTypes('INSURANCE/GET_INSURANCE_DETAIL'),
  GET_INSURANCE_ORDER_FORM: asyncTypes('INSURANCE/GET_INSURANCE_ORDER_FORM'),
  GET_LIST_RESPONSES: asyncTypes('INSURANCE/GET_LIST_RESPONSES'),
  GET_INSUARANCE_REFUND_CONFIG: asyncTypes('INSURANCE/GET_INSUARANCE_REFUND_CONFIG'),
  CREATE_INSURANCE_PAYMENT_TRANSACTION: asyncTypes(
    'INSURANCE/CREATE_INSURANCE_PAYMENT_TRANSACTION'
  ),
  CREATE_INSURANCE_ORDER: asyncTypes('INSURANCE/CREATE_INSURANCE_ORDER'),
  EDIT_INSURANCE_ORDER: asyncTypes('INSURANCE/EDIT_INSURANCE_ORDER'),
  GET_INSURANCE_ORDER_FORM_FOR_CREATE: asyncTypes('INSURANCE/GET_INSURANCE_ORDER_FORM_FOR_CREATE'),
  GET_INSURANCE_ORDER_FORM_FOR_EDIT: asyncTypes('INSURANCE/GET_INSURANCE_ORDER_FORM_FOR_EDIT')
};

export const ADDITIONAL_SERVICE_PROFILE_DETAILS = {
  GET_DETAILS: asyncTypes('ADDITIONAL_SERVICE_PROFILE_DETAILS/GET_DETAILS'),
  CANCEL_PROFILE: asyncTypes('ADDITIONAL_SERVICE_PROFILE_DETAILS/CANCEL_PROFILE'),
  PREPAYMENT: asyncTypes('ADDITIONAL_SERVICE_PROFILE_DETAILS/PREPAYMENT')
};

export const SCHEDULE = {
  GET_LIST: asyncTypes('SCHEDULE/GET_LIST'),
  CREATE_OR_EDIT: asyncTypes('SCHEDULE/CREATE_OR_EDIT'),
  DELETE: asyncTypes('SCHEDULE/DELETE'),
  GET_DETAIL: asyncTypes('SCHEDULE/GET_DETAIL'),
  UPDATE_STATUS: asyncTypes('SCHEDULE/UPDATE_STATUS'),
  GET_LIST_IN_LEAD: asyncTypes('SCHEDULE/GET_LIST_IN_LEAD'),
  GET_LIST_IN_FINANCE: asyncTypes('SCHEDULE/GET_LIST_IN_FINANCE'),
  EXPORT_FILE: asyncTypes('SCHEDULE/EXPORT_FILE')
};
export const INVOICE = {
  CREATE_OR_EDIT_INVOICE: asyncTypes('INVOICE/CREATE_OR_EDIT_INVOICE'),
  GET_ALL_INVOICE: asyncTypes('INVOICE/GET_ALL_INVOICE'),
  GET_ALL_TRANSACTION: asyncTypes('INVOICE/GET_ALL_TRANSACTION'),
  CREATE_UPGRADE_TOPENER_TRANSACTION: asyncTypes('INVOICE/CREATE_UPGRADE_TOPENER_TRANSACTION')
};

export const SETTINGS = {
  CHANGE_LANGUAGE: asyncTypes('SETTINGS/CHANGE_LANGUAGE')
};

export const CASHOUT = {
  CREATE_OR_EDIT_TRANSACTION: asyncTypes('CASHOUT/CREATE_OR_EDIT_TRANSACTION'),
  GET_TRANSACTION_BY_ID: asyncTypes('CASHOUT/GET_TRANSACTION_BY_ID'),
  GET_ALL_GLOBAL_CONFIG: asyncTypes('CASHOUT/GET_ALL_GLOBAL_CONFIG'),
  CREATE_OR_EDIT_ADVANCE_COMMISSION: asyncTypes('CASHOUT/CREATE_OR_EDIT_ADVANCE_COMMISSION'),
  GET_ADVANCE_TRANSACTION: asyncTypes('CASHOUT/GET_ADVANCE_TRANSACTION')
};

export const DEPOSIT = {
  GET_DEPOSIT_MONEY: asyncTypes('DEPOSIT/GET_DEPOSIT_MONEY'),
  CREATE_OR_EDIT: asyncTypes('DEPOSIT/CREATE_OR_EDIT'),
  GET_LIST_REFUND_REQUEST: asyncTypes('DEPOSIT/GET_LIST_REFUND_REQUEST'),
  GET_SUMMARY_TRANSACTION: asyncTypes('DEPOSIT/GET_SUMMARY_TRANSACTION_COUNT'),
  GET_SUMMARY_INSURANCE: asyncTypes('DEPOSIT/GET_SUMMARY_INSURANCE_COUNT')
};

export const TOOGLE_FEATURE = {
  GET_TOOGLE_FEATURE: asyncTypes('TOOGLE_FEATURE/GET_TOOGLE_FEATURE')
};

export const GROUP_TOPENER = {
  GET_GROUP_BY_TOPENER: asyncTypes('GROUP_TOPENER/GET_GROUP_BY_TOPENER'),
  GET_GROUP_FOR_MEMBER: asyncTypes('GROUP_TOPENER/GET_GROUP_FOR_MEMBER'),
  GET_LIST_REQUEST_OR_MEMBER: asyncTypes('GROUP_TOPENER/GET_LIST_REQUEST_OR_MEMBER'),
  GET_LIST_REQUEST_OR_MEMBER_JOIN: asyncTypes('GROUP_TOPENER/GET_LIST_REQUEST_OR_MEMBER_JOIN'),
  GET_LIST_REQUEST_OR_MEMBER_LEAVE: asyncTypes('GROUP_TOPENER/GET_LIST_REQUEST_OR_MEMBER_LEAVE'),
  CREATE_MEMBER_REQUEST: asyncTypes('GROUP_TOPENER/CREATE_MEMBER_REQUEST'),
  GET_MEMBER_INFO_DETAIL: asyncTypes('GROUP_TOPENER/GET_MEMBER_INFO_DETAIL'),
  GET_GROUP_BY_ID: asyncTypes('GROUP_TOPENER/GET_GROUP_BY_ID'),
  PROCESS_REQUEST: asyncTypes('GROUP_TOPENER/PROCESS_REQUEST'),
  DELETE_MEMBER_GROUP_TOPENER: asyncTypes('GROUP_TOPENER/DELETE_MEMBER_GROUP_TOPENER')
};

export const KPI = {
  GET_PERSONAL_KPI_LIST: asyncTypes('KPI/GET_PERSONAL_KPI_LIST'),
  GET_PERSONAL_KPI_DETAIL: asyncTypes('KPI/GET_PERSONAL_KPI_DETAIL'),
  GET_GROUP_KPI_DETAIL: asyncTypes('KPI/GET_GROUP_KPI_DETAIL'),
  GET_GROUP_KPI_LIST: asyncTypes('KPI/GET_GROUP_KPI_LIST'),
  GET_PERSONAL_KPI_STATUS_SUMARY: asyncTypes('KPI/GET_PERSONAL_KPI_STATUS_SUMARY'),
  GET_GROUP_KPI_STATUS_SUMARY: asyncTypes('KPI/GET_GROUP_KPI_STATUS_SUMARY')
};

export const LINK = {
  GET_LINK: asyncTypes('LINK/GET_LINK')
};
